### PR TITLE
Mod updates and cleanup

### PR DESCRIPTION
**Pull request by watama1299**
Updated mods:
- BetterF3
- Not Enough Crashes

Other changes:
- Spelling mistakes
- Move BetterF3, Blur and Borderless Mining to HUD & Menu Enchancements
- Move Zoomify to Camera Enhancements
- Move Not Enough Crashes to Misc Enhancements
- Remove duplicate mods in Outdated/Disabled

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]
Looks good to me.

**Comment by kristofbolyai** [comment]
Although, I wonder if this breaks live installs because of the renames. So I can't merge this atm, I will test it tomorrow.

**Comment by watama1299** [comment]
> Although, I wonder if this breaks live installs because of the renames. So I can't merge this atm, I will test it tomorrow.

I'm guessing that it would. I hope not because it'll be a hassle for everyone, both the devs and the users.

**Comment by kristofbolyai** [comment]
Sadly this could not be done with old launchy, and it will be fixed with 1.5. Thank you for the effort, though.

**Pull request closed without merging**
