### PR TITLE
Remove Physics Mod

### PR DESCRIPTION
**Pull request by MenacingPerson**
Tons of bugs, causes crashes in wynncraft, etc etc

Also, the license was AAR when it should be ARR, but I don't suppose that matters now

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Can this be fixed with some configs?

**Comment by MenacingPerson** [comment]
I don't know. it needs some research/time/effort to figure out, though the answer is probably "yes".

But which config? That's unknown.

**Comment by kristofbolyai** [comment]
@Rafii2198 What do you think? Should we remove it?

**Comment by Rafii2198** [comment]
I include Physics mod in my modpack with a config and I never got a report of it crashing the game, but well it is an optional mod so maybe not everyone enables it and also some reports on the server could be from my modpack too. I honestly don't know what is the right choice. But also the more I play with it, the more annoying it gets. Actually, to make it most comfortable all that is left really is like mob ragdolls, everything else needs to be disabled.

**Review by kristofbolyai — APPROVED** [review]
Let's remove it then.

**Pull request merged**
