### PR TITLE
feat: Added FancyMenu and its dependencies

### PR DESCRIPTION
**Pull request by sofiedotcafe**
Added FancyMenu, Konkrete and Load My Resources
#32

### CODE REVIEW

**Comment by sofiedotcafe** [comment]
https://github.com/Wynntils/launchy-config/pull/1

**Comment by DevScyu** [comment]
I don't think that this is really needed

**Comment by sofiedotcafe** [comment]
> I don't think that this is really needed

But like this would be good, I would not have to maintain my own modpack anymore then. Even an option for this? @DevScyu

**Comment by kristofbolyai** [comment]
This is not something for launchy.

**Comment by sofiedotcafe** [comment]
> This is not something for launchy.

Yea. when I think about it more

**Pull request closed without merging**
